name: Starter CI (ktfmt&build)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ktfmt-build:
    name: ktfmt and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktfmt check
        run: ./gradlew ktfmtCheck

      - name: Build the project
        run: ./gradlew build